### ISSUE TITLE
GAN training

### ISSUE THREAD

**Issue by umichyp** [pclucas14/GansFallingShort#4]
While using best_mle parameters, I found this code also use GAN for training.

**Comment by pclucas14** [comment]
Hi @umichyp, 

If you run something like `python main.py --load_gen_path trained_models/news/word/best_mle`, you are loading weights of a pretrained model, (and not a hyperparameter configuration). This means that the number of adversarial epochs is still calculated from `args.adv_epochs`. Since the default flag for this is > 0, there will be adversarial training. 

If you wish to load the hyperparameter configuration to reproduce `best_mle`, you can have a look at the hyperparameter values in `trained_models/news/word/best_mle/args.json`

-Lucas
