### ISSUE TITLE
Which arg should I follow to train SEQGAN?

### ISSUE THREAD

**Issue by cloudygoose** [pclucas14/GansFallingShort#5]
Hi,

Sorry one more question, 
Which arg should I follow to train SEQGAN(not leakGAN)?
Is it the one in real_data_experiments/trained_models/news/word/best_gan/args.json?
Note that "seqgan_reward": 0, so I guess that's for leakGAN?

Thanks!

**Comment by pclucas14** [comment]
since the execution structure for leakgan is different, we train it in a separate file `main_leak.py` The `--seqgan reward` flag gives the same reward to all timesteps, while setting this flag to false gives a per timestep reward (as described in MaskGan). 

If you want to do SEQGAN (not leakGAN), you can just set `--seqgan_reward 1`. Note that our implementation does not do K Monte Carlo rollouts at every timestep, only 1

**Comment by cloudygoose** [comment]
That's good to know, thanks!
Other than seqgan_reward, is there any other hyper-parameter needed to be changed(For the results in your paper, are you using the same hyper-parameters for seqgan and leakgan)?

**Comment by pclucas14** [comment]
Our best performing GANs were all without LeakGAN. (In my personal opinion), having a leaked signal does not help training. This finding is concurrent with https://openreview.net/pdf?id=rJMcdsA5FX. 

For a complete list of the GAN hparams, please have a look at 
https://github.com/pclucas14/GansFallingShort/blob/master/real_data_experiments/trained_models/news/word/best_gan/args.json
